name: tests-plants

on:
  pull_request:
    paths:
      - "plants/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd plants && npm install && npm run test:ci
